[package]
name = "hyperlane_init"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
hyperlane.workspace = true
hyperlane_app.workspace = true
hyperlane_config.workspace = true
hyperlane_plugin.workspace = true
