[package]
name = "hyperlane_app"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
hyperlane_config = { workspace = true }
hyperlane_plugin = { workspace = true }

hyperlane = { workspace = true }
hyperlane-utils = { workspace = true }
